### PR TITLE
Update docfx from v2.45.1 --> 2.56.1

### PR DESCRIPTION
**Pull request by SeanKilleen**
Updates docfx to the lastest release.

I believe this version includes several bugfixes, one of which is related to https://github.com/nunit/docs/issues/448.

### CODE REVIEW

**Comment by nikeee** [comment]
Thank you!

**Comment by nikeee** [comment]
A reference if something pops up: we hat some issues with newer versions of DocFX in #1. The solution then was downgrading.

**Comment by uweenukr** [comment]
had to rollback to fix issue from latest.

**Comment by nikeee** [comment]
We're back at 2.45.1 as long as dotnet/docfx#5785 isn't fixed.

**Comment by SeanKilleen** [comment]
No worries, I was unaware of that issue.

I forked the project to make the updates since we're not impacted by that. In the future, I'll try to submit a PR where the docfx version can be parameterized and tagged separately so that releases of the tool across many docfx versions will be possible. 👍

**Pull request merged**
